window.PROJECTS = [
  {
    id:"cma-enterprise-data-platform", order:1, company:"Google Cloud | Deployed at CMA CGM HQ, Marseille", category:"cma", featured:true, spotlight:true,
    kicker:"ENTERPRISE DATA FOUNDATION", title:"CMA CGM Enterprise Data & Decision Platform",
    subtitle:"BigQuery · Cloud Dataflow · SQL · governed transformations · data quality · executive analytics",
    metric:"8", metricLabel:"business units connected", scale:"12 countries · enterprise operational + commercial data",
    roleSummary:"As a Google Cloud consultant focused on Data & AI/ML and deployed at CMA CGM HQ, I worked across the data lifecycle: ingestion, transformation, data quality, analytics, ML-ready datasets, executive insight and production monitoring.",
    impact:"The platform turned fragmented operational and commercial data into governed analytical products used for decision support. Data-quality controls contributed to a 35% reduction in inconsistencies, while analytics and automation initiatives contributed to €2.3M in annual efficiency savings.",
    tags:["Google Cloud","BigQuery","Cloud Dataflow","SQL","Data Quality","DataHub","Executive Analytics","ETL / ELT"],
    cardFlow:["Sources","Ingest","Transform","Govern","Decide"],
    problem:"Enterprise decisions depended on data arriving from multiple operational, commercial and third-party sources with different structures, ownership and quality. The challenge was not simply moving data into a warehouse; it was creating a trusted analytical layer that leaders and downstream ML use cases could rely on.",
    before:[
      "Operational and commercial data arrived from multiple systems with inconsistent structures and definitions.",
      "Manual reconciliation and fragmented reporting slowed analysis and weakened confidence in numbers.",
      "Data quality issues were often discovered downstream, after dashboards or models had already consumed the data.",
      "Analytics teams needed reusable, business-ready datasets rather than repeatedly rebuilding logic for each request."
    ],
    after:[
      "Cloud Dataflow and controlled ingestion patterns move data into governed analytical layers.",
      "BigQuery and SQL transformations standardise business logic into reusable curated datasets.",
      "Data-quality checks, ownership and DataHub documentation make quality and lineage explicit.",
      "Dashboards, ML features and decision services consume the same trusted analytical foundation.",
      "Freshness, failure and business KPIs are monitored so the platform can be operated, not just built."
    ],
    beforeArchitecture:["ERP / ops sources","Manual extracts","Local spreadsheets","Repeated SQL logic","Inconsistent KPI views","Late quality fixes"],
    afterArchitecture:["Batch / API sources","Dataflow ingestion","BigQuery layers","DQ + DataHub","Analytics / ML marts","Dashboards + decisions"],
    architectureChange:[
      "Separate raw ingestion from business-ready transformation so source volatility does not leak directly into decision products.",
      "Create reusable analytical models and KPI logic instead of rebuilding definitions inside every dashboard.",
      "Move data quality upstream with completeness, validity and reconciliation checks before consumption.",
      "Make ownership, lineage and operational monitoring part of the platform architecture.",
      "Design the same governed data foundation to support both BI and ML use cases."
    ],
    contribution:[
      "Designed and implemented production data pipelines using Cloud Dataflow and BigQuery across operational and commercial domains.",
      "Developed layered transformation patterns from raw and staged data to business-ready analytical models.",
      "Implemented data-quality controls and governance practices that contributed to a 35% reduction in data inconsistencies.",
      "Built decision-ready datasets and dashboards used across business units and countries.",
      "Supported ML and AI-ready downstream use cases by structuring reliable feature and document data.",
      "Connected technical delivery to executive reporting and benefit realisation, contributing to €2.3M in annual efficiency savings."
    ],
    runtime:[
      ["Source","Operational + commercial data","Transactional, operational and third-party data enters through defined source contracts.","data"],
      ["Ingest","Dataflow / API / batch","Extract and load data through repeatable ingestion paths with timestamps and run metadata.","system"],
      ["Validate","Quality gate","Check schema, completeness, validity and critical reconciliation rules before promotion.","quality"],
      ["Transform","BigQuery + SQL","Standardise keys, dimensions, business rules and metrics into reusable curated layers.","process"],
      ["Govern","DataHub + ownership","Document dataset meaning, lineage, owners and access expectations.","control"],
      ["Consume","BI + ML features","Expose trusted data to dashboards, analysis, forecasting and machine-learning workflows.","data"],
      ["Decide","Executive / operational action","Translate analytical outputs into business decisions, prioritisation and interventions.","human"],
      ["Monitor","Freshness + quality + value","Track pipeline health, data quality and whether the analytical product is creating business value.","outcome"]
    ],
    architecture:[
      ["SOURCES","ERP · operations · commercial · APIs","Structured and external enterprise signals"],
      ["INGESTION","Cloud Dataflow · batch · REST","Controlled extraction and movement"],
      ["LANDING","Cloud Storage / BigQuery raw","Immutable or staged source representation"],
      ["TRANSFORM","BigQuery · SQL · dbt-style layers","Standardisation and business logic"],
      ["QUALITY","Validation · reconciliation","Completeness · validity · consistency"],
      ["GOVERNANCE","DataHub · RBAC · lineage","Ownership · access · auditability"],
      ["ANALYTICS","Curated marts · KPI layer","Reusable decision-ready models"],
      ["CONSUMPTION","Power BI / Qlik / ML services","Dashboards · analysis · model features"],
      ["OBSERVABILITY","Freshness · errors · SLA","Production monitoring and feedback"]
    ],
    controls:["Schema validation","Completeness checks","Reconciliation","Freshness SLA","Dataset ownership","RBAC","Lineage documentation","Audit trail","Pipeline monitoring","KPI definition governance"],
    toolGroups:[
      ["Data engineering",["BigQuery","Cloud Dataflow","SQL","Python","Cloud Storage","REST APIs"]],
      ["Transformation",["Layered data models","dbt methodology","Business rules","Dimensional modelling","KPI layers"]],
      ["Governance",["Data quality","DataHub","RBAC","Lineage","Audit evidence"]],
      ["Consumption",["Power BI","Qlik Sense","Executive reporting","ML-ready datasets"]]
    ],
    artifacts:["Source-to-target mapping","Pipeline design","Transformation model","Data-quality rulebook","KPI dictionary","DataHub documentation","Executive dashboard","Pipeline health dashboard","Runbook"],
    decisions:[
      "Treat data quality as an architectural layer, not a downstream clean-up activity.",
      "Separate raw, staged and business-ready data so changes remain traceable.",
      "Reuse governed KPI logic across dashboards and analysis instead of embedding definitions in presentation layers.",
      "Design for operational ownership from day one: monitoring, lineage, access and runbooks are part of delivery."
    ]
  },
  {
    id:"cma-risk-propensity", order:2, company:"Google Cloud | CMA CGM Financial Services context", category:"ml", featured:true,
    kicker:"RISK + OPPORTUNITY ANALYTICS", title:"Transactional Analytics, Propensity & Risk Signals",
    subtitle:"Python · SQL · statistical analysis · anomaly detection · propensity modelling · forecasting",
    metric:"C-SUITE", metricLabel:"decision-support cadence", scale:"Commercial · treasury · compliance · operational analytics",
    roleSummary:"Built analytical and ML workflows that transformed complex transactional data into risk, opportunity and planning signals, then translated those outputs into recommendations for business stakeholders.",
    impact:"The value was not the model score itself; it was the ability to identify patterns, prioritise investigation or opportunity, explain the drivers and connect the result to a business action with measurable follow-through.",
    tags:["Propensity Modelling","Risk Analytics","Anomaly Detection","Forecasting","Python","SQL","Model Evaluation","Decision Intelligence"],
    cardFlow:["Question","Features","Model","Explain","Action"],
    problem:"Large transactional datasets contain weak signals that are difficult to identify through static reporting alone. Business teams needed a structured way to detect risk, prioritise opportunity and understand what action should follow from the analysis.",
    before:[
      "Analysts relied heavily on retrospective KPI views and manual investigation.",
      "Potential risk or opportunity was difficult to prioritise across large volumes of transactions.",
      "Model outputs could become black boxes if business drivers and thresholds were not explained.",
      "A score without an action path created analytical output but not operational value."
    ],
    after:[
      "Define the decision first: what risk, opportunity or behaviour needs to be predicted or detected?",
      "Build features from governed transactional, behavioural and external signals.",
      "Score or detect patterns using statistical / ML methods appropriate to the use case.",
      "Pair model output with thresholds, drivers and human-review paths.",
      "Monitor both model effectiveness and downstream business outcome."
    ],
    beforeArchitecture:["Transactions","Manual slicing","Static KPI","Analyst judgement","Ad-hoc action"],
    afterArchitecture:["Feature layer","Model / rules","Score + drivers","Review / threshold","Business action","Outcome feedback"],
    architectureChange:[
      "Move from descriptive-only reporting to decision-oriented analytical products.",
      "Create a reusable feature layer so model logic is consistent and testable.",
      "Separate model score from decision policy; thresholds and human review remain explicit controls.",
      "Add post-decision feedback so model evaluation includes business outcomes, not only technical metrics."
    ],
    contribution:[
      "Conducted in-depth analysis of complex transactional and financial datasets using Python and SQL.",
      "Developed modelling approaches for propensity, anomaly detection, forecasting and risk mitigation use cases.",
      "Evaluated model effectiveness using production performance signals and recommended improvements.",
      "Translated model findings into executive narratives and strategy recommendations for finance, operations and compliance stakeholders.",
      "Integrated internal and external signals to enrich model features and analytical context."
    ],
    runtime:[
      ["Frame","Decision question","Start from the business decision: detect risk, identify opportunity or forecast an outcome.","human"],
      ["Build","Feature set","Create governed behavioural, transactional and contextual features.","data"],
      ["Train","Model / statistical logic","Fit and validate the method against historical outcomes and appropriate baselines.","ai"],
      ["Score","Risk / propensity signal","Generate a calibrated score, ranking or anomaly signal.","system"],
      ["Explain","Drivers + thresholds","Expose why the signal matters and what confidence or threshold applies.","control"],
      ["Review","Human decision point","Route material or ambiguous cases to the right stakeholder for confirmation.","human"],
      ["Act","Business intervention","Prioritise an investigation, opportunity, campaign, mitigation or planning action.","outcome"],
      ["Learn","Outcome feedback","Measure precision, false positives, lift, forecast error and business value over time.","data"]
    ],
    architecture:[
      ["INPUT","Transactional + demographic + external","Governed analytical signals"],
      ["FEATURES","SQL / Python feature layer","Aggregations · trends · behavioural variables"],
      ["MODEL","Propensity · anomaly · forecast","Use-case appropriate statistical / ML logic"],
      ["VALIDATION","Back-test + holdout + business rules","Technical and domain validation"],
      ["SCORING","Score / rank / alert","Decision signal"],
      ["EXPLANATION","Drivers + reason codes","Interpretability for users"],
      ["DECISION","Threshold + human review","Controlled intervention"],
      ["MONITORING","Drift + outcome metrics","Continuous evaluation"]
    ],
    controls:["Train / validation split","Baseline comparison","Threshold governance","False-positive review","Model drift","Feature quality","Human review","Outcome tracking","Versioning"],
    toolGroups:[
      ["Analytics",["Python","SQL","Pandas","Statistical analysis","Data mining"]],
      ["ML",["scikit-learn","Propensity modelling","Anomaly detection","Forecasting","NLP"]],
      ["Evaluation",["Precision / recall","Lift","Forecast error","Back-testing","Production monitoring"]],
      ["Decision",["Executive reporting","Business thresholds","Human review","Recommendations"]]
    ],
    artifacts:["Business question / hypothesis","Feature dictionary","Model notebook / pipeline","Validation report","Threshold proposal","Executive insight pack","Monitoring dashboard","Outcome review"],
    decisions:[
      "Define the action before choosing the algorithm.",
      "Use the simplest model that produces a reliable and explainable decision signal.",
      "Keep thresholds and business policy outside the model so they can be governed independently.",
      "Evaluate success on business lift and decision quality as well as model metrics."
    ]
  },
  {
    id:"cma-external-data", order:3, company:"Google Cloud | Deployed at CMA CGM HQ", category:"data", featured:true,
    kicker:"EXTERNAL DATA INTEGRATION", title:"Market Signals & Third-Party Data Enrichment",
    subtitle:"REST APIs · external feeds · entity resolution · validation · enrichment · governed consumption",
    metric:"MULTI", metricLabel:"source types integrated", scale:"Internal + external analytical context",
    roleSummary:"Integrated external financial, market and vendor data with internal operational datasets so analysis and models could use a richer view of context without compromising quality or traceability.",
    impact:"External data becomes useful only when it can be mapped to internal entities, validated, refreshed predictably and traced to its source. The project pattern created a governed enrichment layer rather than uncontrolled spreadsheet joins.",
    tags:["External Data","REST APIs","Entity Resolution","Data Quality","Market Signals","Third-Party Vendors","Lineage"],
    cardFlow:["Acquire","Validate","Match","Enrich","Use"],
    problem:"Public, vendor and market data can improve analytical context, but source schemas, identifiers, refresh schedules and quality expectations rarely align with internal enterprise data.",
    before:["External signals were consumed ad hoc.","Identifiers did not always align with internal customer, account or business entities.","Refresh and provenance were difficult to audit.","Analysts could unknowingly combine stale or low-quality data with trusted internal metrics."],
    after:["Source contracts define field meaning, cadence and failure behaviour.","Validation profiles each incoming feed before promotion.","Entity-resolution logic links external records to governed internal entities.","Enriched datasets preserve source, timestamp and lineage.","Models and dashboards consume approved enrichment layers rather than raw external feeds."],
    beforeArchitecture:["Vendor file / API","Ad-hoc join","Analyst spreadsheet","Unclear match","No provenance"],
    afterArchitecture:["Source contract","API ingestion","Validation","Entity match","Enrichment layer","Governed consumer"],
    architectureChange:["Create source-specific ingestion adapters while standardising the downstream contract.","Treat entity matching as an explicit data product with confidence and exception handling.","Persist source and acquisition metadata for auditability.","Protect downstream consumers from schema changes through a curated enrichment layer."],
    contribution:["Connected external financial data, market signals and third-party API feeds to internal analytical data.","Defined validation and transformation steps before external data reached decision products.","Mapped external records to internal business entities and analytical dimensions.","Used enriched data to improve analytics, model features and executive context."],
    runtime:[
      ["Acquire","API / vendor feed","Collect data under a defined refresh and source contract.","system"],
      ["Profile","Schema + quality","Check completeness, types, value ranges and freshness.","quality"],
      ["Standardise","Canonical fields","Normalise dates, currencies, identifiers and categorical values.","process"],
      ["Resolve","Entity matching","Link the external record to an internal account, customer, market or product entity.","ai"],
      ["Review","Low-confidence matches","Route ambiguous matches to a controlled exception path.","human"],
      ["Enrich","Curated dataset","Join approved external context to internal analytical models.","data"],
      ["Consume","Analytics / model","Use the enriched data for analysis, scoring or forecasting.","outcome"],
      ["Monitor","Freshness + vendor health","Detect source failures, stale feeds and match-quality degradation.","control"]
    ],
    architecture:[["EXTERNAL","Public / vendor / market sources","API · file · database"],["INGEST","REST / batch connector","Authentication · retries · metadata"],["VALIDATE","Schema + quality profile","Freshness · completeness · range"],["RESOLVE","Entity matching","Rules · fuzzy match · confidence"],["CURATE","Enrichment layer","Canonical dimensions + provenance"],["CONSUME","BI / ML / executive analysis","Approved downstream use"],["MONITOR","Source health + match quality","Operational control"]],
    controls:["Source contract","Authentication","Schema checks","Freshness","Currency / date standardisation","Entity-match confidence","Exception queue","Provenance","Vendor SLA"],
    toolGroups:[["Integration",["REST APIs","Batch files","Python","SQL"]],["Quality",["Schema validation","Profiling","Freshness checks","Reconciliation"]],["Resolution",["Entity keys","Matching rules","Confidence scoring","Exception handling"]],["Governance",["Lineage","Source metadata","Access controls","Vendor monitoring"]]],
    artifacts:["Source inventory","API mapping","Canonical schema","Entity-resolution rules","Match-quality report","Enrichment dataset","Lineage record","Vendor health dashboard"],
    decisions:["Never mix external and internal data without preserving provenance.","Use deterministic identifiers first; use fuzzy logic only when necessary and reviewable.","Quarantine source anomalies before they contaminate trusted analytical products.","Monitor external data as an operational dependency, not a one-time dataset."]
  },
  {
    id:"cma-document-ai", order:4, company:"Google Cloud | CMA CGM context", category:"ai", featured:false,
    kicker:"DOCUMENT INTELLIGENCE + RAG", title:"AI-Ready Document & Knowledge Workflows",
    subtitle:"NLP · embeddings · retrieval · structured extraction · human review · API serving",
    metric:"AI", metricLabel:"knowledge-to-action workflow", scale:"Commercial · compliance · operational document context",
    roleSummary:"Built AI-ready data and workflow patterns for document processing, extraction, retrieval and downstream decision support, combining deterministic quality controls with NLP / embedding based retrieval.",
    impact:"The pattern reduced the gap between unstructured enterprise content and usable decision context: documents are parsed, structured, indexed, retrieved and reviewed through explicit quality and human-control gates.",
    tags:["NLP","Embeddings","RAG","Document Processing","GCP AI","Cloud Run","Human-in-the-loop","AI Governance"],
    cardFlow:["Parse","Extract","Index","Retrieve","Review"],
    problem:"Important operational and commercial knowledge often lives in contracts, transport documents, correspondence and policy content that cannot be queried reliably through structured SQL alone.",
    before:["Users manually searched long documents and archives.","Key fields were repeatedly re-keyed into structured systems.","Search relied on filenames or exact keywords rather than semantic meaning.","Generated answers could be unsafe if source evidence and confidence were not visible."],
    after:["Documents are parsed and normalised before AI processing.","Entity and field extraction converts high-value content into structured data.","Embeddings support semantic retrieval over approved knowledge.","Retrieval evidence is preserved so answers can be grounded in source context.","Low-confidence or consequential outputs retain a human-review path."],
    beforeArchitecture:["Document store","Manual search","Copy / paste","Local interpretation","Manual action"],
    afterArchitecture:["Parse","Extract","Chunk / embed","Vector retrieval","Grounded response","Review / action"],
    architectureChange:["Separate document parsing and extraction from generative output.","Maintain chunk / source metadata so retrieved context remains traceable.","Use retrieval before generation so answers are grounded in approved enterprise knowledge.","Keep human review and deterministic rules for low-confidence or high-impact cases.","Expose the capability behind an API / service boundary so it can be reused by multiple applications."],
    contribution:["Worked on ETL and AI-ready data flows for NLP, embeddings and RAG-style workflows.","Supported structured document and entity-extraction pipelines for downstream analytics and automation.","Applied source metadata, validation and human review to keep AI outputs auditable.","Used cloud serving patterns to make document intelligence reusable by business applications."],
    runtime:[["Ingest","Document intake","Receive approved documents and preserve source metadata.","data"],["Parse","Text + structure","Extract machine-readable content and page / section context.","process"],["Extract","Entities + fields","Identify structured values needed by downstream processes.","ai"],["Embed","Semantic index","Create vector representations for approved content.","ai"],["Retrieve","Relevant evidence","Find the most relevant source passages for a question or task.","system"],["Generate","Grounded output","Produce an answer or recommendation constrained by retrieved evidence.","ai"],["Review","Confidence + human control","Escalate ambiguous or high-impact outcomes.","control"],["Act","Business workflow","Pass structured output to an application, analyst or automation.","outcome"]],
    architecture:[["CONTENT","Contracts · documents · policies","Approved enterprise knowledge"],["PARSE","Document processing","Text · layout · metadata"],["EXTRACT","NLP / entity extraction","Structured fields"],["INDEX","Embeddings / vector store","Semantic representation"],["RETRIEVE","Search / ranking","Evidence selection"],["GENERATE","LLM / agent layer","Grounded response"],["CONTROL","Confidence + human review","Safety and quality"],["SERVE","Cloud Run / API","Reusable business capability"]],
    controls:["Source allow-list","PII / access controls","Chunk provenance","Extraction validation","Retrieval evidence","Prompt / model versioning","Confidence threshold","Human review","Feedback capture"],
    toolGroups:[["AI",["NLP","Embeddings","RAG","GCP AI / embedding patterns","LLMs"]],["Data",["Python","SQL","Document parsing","Structured extraction"]],["Serving",["Cloud Run","REST APIs","Containerised deployment"]],["Governance",["Source provenance","Human review","Access control","Evaluation"]]],
    artifacts:["Document taxonomy","Extraction schema","Chunking / metadata design","Retrieval evaluation set","Prompt / response template","Human-review rule","API contract","AI quality dashboard"],
    decisions:["Use deterministic extraction where a field can be defined exactly; use generative AI only where ambiguity requires it.","Never return an enterprise answer without preserving the evidence used to produce it.","Separate retrieval quality from generation quality so failures can be diagnosed correctly.","Treat human review as a designed control, not an emergency fallback."]
  },
  {
    id:"volvo-data-platform", order:5, company:"Volvo Group | Bengaluru", category:"volvo", featured:true,
    kicker:"LARGE-SCALE SUPPLY CHAIN DATA", title:"Volvo Supply Chain ETL & ML Platform",
    subtitle:"Azure Databricks · PySpark · Informatica integration · Spark MLlib · production data quality",
    metric:"500M+", metricLabel:"rows processed per month", scale:"Supply-chain and procurement analytics",
    roleSummary:"Built and maintained PySpark / ML pipelines over large supply-chain datasets, integrating ERP-sourced and operational data into analytics and machine-learning workflows used for planning and optimisation.",
    impact:"The platform supported high-volume analytical and ML workloads while improving the reliability of supply-chain decision inputs. The work connected data engineering directly to forecasting, classification, recommendation and inventory decisions.",
    tags:["Azure Databricks","PySpark","Informatica-based integration","Spark MLlib","ETL","Supply Chain","Data Quality","ML Lifecycle"],
    cardFlow:["ERP","ETL","Curate","Model","Plan"],
    problem:"Supply-chain decisions depended on large volumes of ERP, procurement and operational data that needed consistent integration, transformation and quality controls before they could support forecasting or machine learning.",
    before:["Data lived across ERP, procurement and operational platforms.","Large-scale transformations were expensive and difficult to reproduce manually.","Data quality issues created noise in downstream forecasts and models.","Planning teams needed analytical outputs that could be refreshed reliably, not one-off analyses."],
    after:["Integration workflows bring source data into a Databricks processing environment.","PySpark transformations standardise and aggregate high-volume supply-chain data.","Quality controls protect model and reporting inputs.","ML pipelines support classification, recommendation and forecasting use cases.","Outputs feed planning and inventory decisions through repeatable production workflows."],
    beforeArchitecture:["ERP / GDMS / VIDA","Extracts","Local transformations","Manual QA","One-off model","Planner"],
    afterArchitecture:["ERP + operational sources","Informatica / ingestion","Databricks / PySpark","DQ layer","ML / forecast","Decision support"],
    architectureChange:["Move heavy transformations into scalable distributed processing.","Standardise source integration before model-specific feature engineering.","Apply quality controls upstream so model performance is not confused with bad data.","Operationalise the ML lifecycle from preparation through deployment and monitoring."],
    contribution:["Built and maintained PySpark ETL pipelines on Azure Databricks processing 500M+ rows per month.","Worked with Informatica-based integration tooling across ERP-integrated and analytics systems.","Developed production ML workflows using scikit-learn and Spark MLlib.","Applied performance optimisation and data-quality controls across supply-chain domains.","Connected model outputs to planning, procurement and inventory decision support."],
    runtime:[["Extract","ERP + operational sources","Acquire orders, inventory, supplier and operational records.","data"],["Integrate","Informatica / connectors","Move data into a standard analytical landing pattern.","system"],["Transform","PySpark","Clean, standardise, join and aggregate high-volume datasets.","process"],["Validate","Quality controls","Check key fields, duplicates, ranges, completeness and reconciliation.","quality"],["Engineer","ML features","Build features for forecast, classification or recommendation use cases.","data"],["Model","Spark MLlib / scikit-learn","Train and validate the selected analytical model.","ai"],["Publish","Decision dataset","Expose forecast, recommendation or KPI outputs to consumers.","system"],["Monitor","Data + model health","Track pipeline quality, model behaviour and business use.","outcome"]],
    architecture:[["SOURCES","ERP · procurement · supply chain","Orders · stock · suppliers · operational events"],["INTEGRATION","Informatica / ingestion","Source extraction and movement"],["PROCESSING","Azure Databricks · PySpark","Distributed transformation"],["QUALITY","Validation + reconciliation","Reliable analytical inputs"],["FEATURES","Curated ML datasets","Time-series · inventory · supplier signals"],["MODELS","Spark MLlib · scikit-learn","Forecast · classify · recommend"],["SERVE","Analytics / planning outputs","Decision support"],["MONITOR","Pipeline + model metrics","Production lifecycle"]],
    controls:["Schema checks","Duplicate control","Null / range checks","Partition strategy","Performance monitoring","Feature consistency","Model evaluation","Run monitoring","Business validation"],
    toolGroups:[["Data",["Azure Databricks","PySpark","SQL","Informatica-based integration"]],["ML",["Spark MLlib","scikit-learn","Forecasting","NLP classification","Recommendation"]],["Engineering",["ETL pipelines","Performance optimisation","Data quality","Monitoring"]],["Domain",["Supply chain","Procurement","Inventory","Planning"]]],
    artifacts:["Source mapping","Databricks pipeline","PySpark transformations","DQ checks","Feature dataset","Model evaluation","Planning output","Production monitoring"],
    decisions:["Scale transformations with distributed processing rather than forcing large datasets through local tooling.","Build quality checks into the pipeline before model training.","Keep feature creation reproducible so retraining and back-testing are consistent.","Judge model usefulness by the planning decision it improves, not only technical accuracy."]
  },
  {
    id:"volvo-inventory-forecasting", order:6, company:"Volvo Group | Bengaluru", category:"volvo", featured:true,
    kicker:"PLANNING + INVENTORY OPTIMISATION", title:"Demand Forecasting & Excess-Stock Reduction",
    subtitle:"SQL · Python · forecasting · KPI analysis · root-cause deep dives · planner feedback",
    metric:"15%", metricLabel:"reduction in excess-stock costs contributed", scale:"Supply-chain + procurement process improvement",
    roleSummary:"Combined operational data analysis, forecasting and process improvement to identify excess-stock drivers, prioritise interventions and support planning decisions across international teams.",
    impact:"The work contributed to a 15% reduction in excess-stock costs by connecting analytical signals with changes in planning, inventory and procurement processes rather than treating the model as a standalone deliverable.",
    tags:["Forecasting","Inventory Optimisation","SQL","Python","KPI Framework","Root Cause","Planning","Business Impact"],
    cardFlow:["Baseline","Forecast","Gap","Action","Measure"],
    problem:"Excess inventory is not a single modelling problem. It can be caused by forecast error, lead-time variability, ordering behaviour, slow-moving items, supplier constraints or master-data issues, so the analytical workflow had to identify the real driver before recommending action.",
    before:["Inventory decisions were difficult to prioritise across many parts and suppliers.","Different root causes could produce the same headline excess-stock symptom.","Forecast output was not sufficient without operational interpretation.","Improvement needed a closed loop between analysis, planners and procurement teams."],
    after:["Segment inventory and demand behaviour before applying one forecasting rule to everything.","Compare forecast, actual demand, stock position and lead-time signals.","Use root-cause views to distinguish demand, supply, ordering and data-quality drivers.","Prioritise planner or procurement actions by expected financial impact.","Measure the effect and feed exceptions back into the next planning cycle."],
    beforeArchitecture:["Demand history","Planner judgement","Static stock view","Manual prioritisation","Reactive action"],
    afterArchitecture:["Demand + inventory + lead time","Forecast / segmentation","Gap analysis","Root cause","Prioritised action","Outcome review"],
    architectureChange:["Join demand, inventory, supplier and lead-time data into one decision dataset.","Separate forecasting from decision policy so business rules remain visible.","Add financial impact to prioritisation rather than ranking only by model error.","Close the loop with planner feedback and realised outcomes."],
    contribution:["Deep-dived supply-chain performance using SQL and Python.","Built forecasting and analytical views supporting planning and inventory decisions.","Produced impact reports and dashboards to identify high-value intervention opportunities.","Worked with teams in Gothenburg and Bengaluru to translate analytical findings into process changes.","Contributed to a 15% reduction in excess-stock costs through analytics and process improvement."],
    runtime:[["Baseline","Demand + stock profile","Measure demand history, inventory position, service target and cost exposure.","data"],["Segment","Behaviour groups","Separate stable, intermittent, seasonal and exceptional patterns.","process"],["Forecast","Expected demand","Generate and back-test a forecast appropriate to the segment.","ai"],["Compare","Forecast vs actual vs stock","Quantify where the current plan creates risk or excess.","data"],["Diagnose","Root cause","Identify whether the driver is demand, lead time, order policy, supplier or data quality.","human"],["Prioritise","Financial impact","Rank interventions by potential cost / service value.","control"],["Act","Planner / procurement change","Adjust parameters, orders, sourcing or exception handling.","outcome"],["Measure","Realised impact","Track stock, service and forecast performance after intervention.","data"]],
    architecture:[["DATA","Demand · inventory · supplier · lead time","Decision inputs"],["ANALYSIS","SQL / Python","Segmentation + root-cause views"],["FORECAST","Time-series / ML","Expected demand"],["GAP","Forecast vs stock / plan","Risk and excess exposure"],["PRIORITY","Financial + operational value","Action ranking"],["ACTION","Planning / procurement","Business intervention"],["FEEDBACK","Actual outcome","Continuous improvement"]],
    controls:["Forecast back-test","Segment-specific error","Outlier handling","Lead-time sanity checks","Planner override trace","Financial impact validation","Post-action review"],
    toolGroups:[["Analytics",["SQL","Python","Forecasting","KPI analysis"]],["Decision",["Inventory segmentation","Root-cause analysis","Impact sizing","Planner feedback"]],["Delivery",["Dashboards","Impact reports","Cross-functional workshops","Continuous improvement"]]],
    artifacts:["Inventory baseline","Forecast evaluation","Root-cause dashboard","Priority matrix","Impact report","Planner action log","Outcome review"],
    decisions:["Do not use one forecast method for every demand pattern.","Explain inventory excess through root cause before changing planning parameters.","Prioritise interventions by business impact, not analytical interest.","Treat planner feedback as data for improving the next model and process cycle."]
  },
  {
    id:"volvo-predictive-maintenance", order:7, company:"Volvo Group | predictive-maintenance project context", category:"ml", featured:false,
    kicker:"PREDICTIVE MAINTENANCE", title:"Connected Asset Signals → Failure-Risk Decision",
    subtitle:"sensor / event data · feature engineering · classification · anomaly signals · maintenance action",
    metric:"ML", metricLabel:"failure-risk workflow", scale:"Representative architecture grounded in Volvo predictive-maintenance context",
    roleSummary:"Applied machine-learning patterns to operational / asset data with a focus on turning telemetry and event history into interpretable maintenance signals and controlled operational action.",
    impact:"The decision pattern is designed to reduce unplanned disruption without creating unnecessary maintenance: collect the right signals, detect meaningful patterns, explain risk, route the case and learn from the repair outcome.",
    tags:["Predictive Maintenance","Connected Data","Anomaly Detection","Classification","Feature Engineering","Human Review","Monitoring"],
    cardFlow:["Sense","Feature","Predict","Review","Maintain"],
    problem:"Predictive maintenance must balance two costly errors: missing a real failure risk and generating too many false alarms that trigger unnecessary service. The analytical system therefore needs both model performance and an operational decision policy.",
    before:["Maintenance is primarily scheduled or reactive.","Single thresholds can miss combinations of weak signals.","High alert volume can overwhelm maintenance teams.","Repair outcomes are not always fed back into model learning."],
    after:["Combine telemetry, fault codes, usage and maintenance history into a feature view.","Use ML / anomaly logic to identify patterns that precede failure.","Rank or threshold cases by operational risk and confidence.","Provide interpretable drivers to maintenance specialists.","Capture repair outcome and false alarms for continuous model improvement."],
    beforeArchitecture:["Sensor threshold","Alarm","Manual diagnosis","Service","No learning loop"],
    afterArchitecture:["Telemetry","Feature window","Risk model","Reason codes","Maintenance review","Outcome feedback"],
    architectureChange:["Move from isolated thresholds to multivariate pattern detection.","Add feature windows that represent recent behaviour rather than single readings.","Keep the maintenance specialist in the decision loop for consequential action.","Capture outcome labels from service events to improve future prediction."],
    contribution:["Worked with ML and large-scale operational data patterns at Volvo Group.","Applied classification, recommendation and forecasting methods in production-oriented workflows.","Used data-quality and monitoring controls as part of the ML lifecycle.","This portfolio architecture is representative and intentionally avoids claiming confidential internal topology."],
    runtime:[["Sense","Telemetry + events","Collect sensor readings, fault codes, mileage and operating context.","data"],["Window","Feature engineering","Aggregate recent behaviour, trends, counts and combinations of signals.","process"],["Predict","Failure-risk model","Estimate the likelihood or severity of an impending issue.","ai"],["Explain","Drivers / reason codes","Show the signal combination behind the risk estimate.","control"],["Triage","Operational threshold","Prioritise cases that justify maintenance attention.","system"],["Review","Maintenance specialist","Validate the recommendation against asset context.","human"],["Act","Service intervention","Schedule inspection or repair before disruption where appropriate.","outcome"],["Learn","Repair outcome","Feed confirmed faults and false alarms back into evaluation.","data"]],
    architecture:[["TELEMETRY","Sensors · faults · usage","Connected asset signals"],["STREAM / BATCH","Event processing","Time-ordered history"],["FEATURES","Windows · trends · combinations","Model inputs"],["MODEL","Classification / anomaly","Risk signal"],["EXPLAIN","Drivers / confidence","Interpretable context"],["DECISION","Threshold + specialist review","Controlled maintenance action"],["FEEDBACK","Repair outcome","Continuous learning"]],
    controls:["Sensor quality","Missing-data handling","Class imbalance","False-positive rate","Calibration","Threshold review","Human confirmation","Outcome labels","Drift monitoring"],
    toolGroups:[["Data",["PySpark","SQL","Time-series features","Operational events"]],["ML",["Classification","Anomaly detection","Feature engineering","Model evaluation"]],["Operations",["Risk ranking","Reason codes","Human review","Maintenance feedback"]]],
    artifacts:["Telemetry data model","Feature-window design","Model validation","Threshold analysis","Reason-code view","Maintenance decision flow","Feedback dataset"],
    decisions:["Optimise the operational trade-off between missed failures and unnecessary interventions.","Use multivariate patterns where single thresholds are insufficient.","Keep model reasoning visible to domain specialists.","Use real repair outcomes as the strongest signal for model improvement."]
  },
  {
    id:"microsoft-classification", order:8, company:"Microsoft | Hyderabad", category:"ml", featured:false,
    kicker:"ML VALIDATION + PRODUCTION SIGN-OFF", title:"Azure AI Classification Pipeline",
    subtitle:"Azure AI · classification · data quality · model validation · stakeholder communication",
    metric:"PROD", metricLabel:"production-oriented validation", scale:"Machine-learning engineering internship",
    roleSummary:"Built and tested classification models on Azure AI services, applied input-quality controls and communicated results to non-technical stakeholders through production sign-off.",
    impact:"The project established an early pattern that remains central to my work: production ML requires trustworthy inputs, measurable validation, clear communication and explicit business acceptance.",
    tags:["Azure AI","Classification","Data Quality","Validation","Stakeholder Sign-Off","ML Lifecycle"],
    cardFlow:["Prepare","Train","Validate","Explain","Approve"],
    problem:"A model that performs well in experimentation can still fail in production if data quality, validation evidence and stakeholder understanding are not controlled.",
    before:["Input quality varied.","Classification was difficult to reproduce consistently.","Technical metrics did not automatically translate into business confidence.","Production readiness lacked an explicit acceptance gate."],
    after:["Data checks protect model inputs.","Training and validation are repeatable.","Performance evidence is translated for non-technical users.","Production sign-off becomes an explicit delivery milestone."],
    beforeArchitecture:["Raw input","Manual interpretation","Inconsistent checks","Result","Stakeholder uncertainty"],
    afterArchitecture:["Quality gate","Azure AI model","Validation","Explanation","Production sign-off"],
    architectureChange:["Make data quality part of the model pipeline.","Separate training from validation evidence.","Translate technical performance into decision relevance.","Require stakeholder acceptance before production use."],
    contribution:["Built classification models using Azure AI services.","Applied data-quality checks before model use.","Validated model results and documented performance.","Communicated results to non-technical stakeholders and supported production sign-off."],
    runtime:[["Prepare","Input + quality","Validate and standardise model input.","quality"],["Train","Classification model","Fit the model on approved training data.","ai"],["Validate","Holdout metrics","Measure performance and failure patterns.","control"],["Explain","Business translation","Communicate what the model can and cannot reliably do.","human"],["Approve","Production sign-off","Release only after technical and stakeholder acceptance.","outcome"]],
    architecture:[["INPUT","Business records","Classification source"],["QUALITY","Validity + completeness","Input protection"],["MODEL","Azure AI","Classification"],["VALIDATION","Metrics + error analysis","Production suitability"],["COMMUNICATION","Stakeholder review","Decision context"],["SIGN-OFF","Release gate","Approved production use"]],
    controls:["Input quality","Validation set","Error analysis","Performance thresholds","Stakeholder acceptance","Release sign-off"],
    toolGroups:[["ML",["Azure AI","Classification"]],["Quality",["Data checks","Validation","Error analysis"]],["Delivery",["Stakeholder communication","Production sign-off"]]],
    artifacts:["Model experiment","Input-quality checks","Validation report","Error analysis","Stakeholder readout","Sign-off evidence"],
    decisions:["Treat data quality as part of model performance.","Do not present one aggregate accuracy metric without understanding errors.","Translate model limitations before asking stakeholders to rely on it.","Use explicit acceptance before production deployment."]
  },

  {
    id:"cma-ai-agent-automation", order:3.1, company:"Google Cloud | Deployed at CMA CGM HQ, Marseille", category:"cma", categories:["ml"], featured:true,
    kicker:"INTELLIGENT WORKFLOW AUTOMATION", title:"AI Agent Automation for Document Processing & Operational Routing",
    subtitle:"Python · API connectors · AI-agent prompts · rules · human review · measurable time saved",
    metric:"8", metricLabel:"business units in automation scope", scale:"Document processing · extraction · routing · operational workflows",
    roleSummary:"Designed and delivered automation patterns that combined deterministic rules, Python processing, API connectors and AI-assisted extraction / classification to remove repetitive administrative work while preserving exception handling and human control.",
    impact:"Automation initiatives contributed to the broader €2.3M annual efficiency-savings programme by reducing repetitive document, extraction and routing effort. The operating model focused on measurable time saved and adoption rather than automation count alone.",
    tags:["AI Agents","Python","REST APIs","Workflow Automation","Document AI","Human Review","Observability","Business Impact"],
    cardFlow:["Trigger","Validate","Rules","AI","Review","Execute"],
    problem:"High-volume administrative workflows mixed deterministic steps with unstructured documents and exceptions. Pure scripting was brittle for variable content, while unconstrained AI would be difficult to trust in operational processes.",
    before:["Users manually opened, interpreted and routed recurring documents or requests.","The same information was re-keyed across multiple systems.","Exceptions were discovered late and depended on individual experience.","There was limited visibility into time saved, failure reasons or recurring friction."],
    after:["Events or documents enter through a defined intake and validation layer.","Deterministic business rules handle deterministic decisions first.","AI is used selectively for extraction, classification or summarisation where content varies.","Confidence / validation gates route uncertain cases to human review.","Approved outputs execute through controlled APIs and every outcome is logged for monitoring and improvement."],
    beforeArchitecture:["Email / document","Manual read","Copy-paste","Manual routing","System update","No feedback loop"],
    afterArchitecture:["Trigger / API","Schema validation","Rules engine","AI extraction","Human exception","Enterprise API","KPI + audit"],
    architectureChange:["Separate deterministic workflow logic from probabilistic AI tasks.","Introduce explicit confidence and validation gates before system actions.","Use APIs for controlled execution instead of manual re-keying.","Persist workflow state and outcomes so failures, time saved and adoption can be measured.","Feed recurring exceptions back into rules, prompts and process design."],
    contribution:["Diagnosed repetitive administrative workflows with functional users and super users.","Built automation logic with Python, API connectors and AI-agent prompts for document processing, extraction and routing.","Defined human-review and exception paths for ambiguous or high-impact cases.","Connected automation outcomes to dashboards and measurable time-saved indicators.","Scaled workflow patterns across multiple business units as part of a broader transformation programme."],
    runtime:[["Trigger","Event / document intake","A file, request, schedule or API event creates a traceable workflow instance.","data"],["Validate","Schema + context","Check required metadata, deduplicate the request and assign correlation context.","quality"],["Rules","Deterministic routing","Apply known business rules before invoking AI.","process"],["AI","Extract / classify / summarise","Use AI only for the variable or unstructured part of the workflow.","ai"],["Review","Confidence / exception gate","Route uncertain or consequential cases to a human reviewer.","human"],["Execute","Controlled API action","Write approved results into the target enterprise system.","system"],["Measure","Time saved + errors + adoption","Track whether the automation actually improves the process in production.","outcome"]],
    architecture:[["INPUT","Documents · forms · events","Business trigger"],["INTAKE","API · queue · validation","Controlled entry"],["RULES","Deterministic logic","Known decisions"],["AI SERVICES","Extract · classify · summarise","Unstructured reasoning"],["QUALITY GATE","Schema · confidence · policy","Safety / reliability"],["HUMAN REVIEW","Exception handling","Accountability"],["EXECUTION","Enterprise APIs","Controlled action"],["OBSERVABILITY","Logs · KPI · alerts","Production learning"]],
    controls:["Idempotency","Schema validation","Business-rule versioning","Confidence threshold","Human review","API permissions","Audit trail","Retry / exception path","Prompt / model version","Time-saved measurement"],
    toolGroups:[["Automation",["Python","REST APIs","Workflow triggers","Queues / state"]],["AI",["AI-agent prompts","Extraction","Classification","Summarisation"]],["Controls",["Validation","Confidence gates","Human review","Audit logs"]],["Measurement",["Time saved","Errors","Adoption","Support themes"]]],
    artifacts:["As-is workflow map","Automation opportunity matrix","Functional specification","API contract","Prompt / rule design","Exception matrix","Test evidence","Adoption dashboard","Runbook"],
    decisions:["Do not use AI for deterministic logic that can be expressed safely as rules.","Never let uncertain AI output silently update a consequential system.","Measure automation through business time saved and process quality, not number of bots.","Treat exceptions as training data for the next process or model iteration."]
  },
  {
    id:"cma-dynamic-pricing", order:3.2, company:"CMA CGM | Commercial analytics project experience", category:"cma", categories:["ml"], featured:true,
    kicker:"COMMERCIAL DECISION INTELLIGENCE", title:"Dynamic Pricing & Commercial Decisioning",
    subtitle:"demand signals · route / voyage context · capacity · historical behaviour · pricing rules · recommendation",
    metric:"ML", metricLabel:"pricing decision workflow", scale:"Commercial pricing · demand / capacity context · governed recommendation",
    roleSummary:"Worked on dynamic-pricing / commercial-analytics patterns where the objective was to turn demand, route, capacity and historical signals into faster pricing recommendations while keeping commercial rules, explainability and human override visible.",
    impact:"The value of the design is not an opaque price prediction. It is a governed decision workflow that gives commercial users a recommendation, the context behind it, the applicable constraints and a measurable downstream outcome such as acceptance, conversion or yield.",
    tags:["Dynamic Pricing","Demand Signals","Forecasting","Commercial Analytics","ML","Business Rules","Explainability","Decision Support"],
    cardFlow:["Context","Features","Forecast","Recommend","Review","Learn"],
    problem:"Spot and commercial pricing must react to changing demand and operational constraints, but pricing decisions also need consistency, commercial guardrails and enough explanation for users to trust the recommendation.",
    before:["Pricing context was spread across demand, route, capacity and historical sources.","Manual interpretation slowed response and could create inconsistent decisions.","A single predicted number would not explain why the recommendation changed.","Learning from accepted, rejected or overridden recommendations was limited."],
    after:["Create one pricing feature view combining commercial and operational context.","Use forecasting / analytical models to estimate demand or relevant future signals.","Apply business rules and commercial guardrails around the model output.","Show key drivers and allow accountable override where required.","Capture quote / booking / override outcomes to improve the next decision cycle."],
    beforeArchitecture:["Demand extracts","Route context","Manual comparison","Price judgement","Quote","Little feedback"],
    afterArchitecture:["Demand + route + capacity","Feature layer","Forecast / model","Rules / guardrails","Recommendation","Commercial review","Outcome feedback"],
    architectureChange:["Bring demand, route, capacity and historical context into a reusable analytical feature layer.","Keep model signal separate from commercial rules so governance remains visible.","Provide reason codes / driver context rather than an unexplained recommendation.","Capture user override and downstream outcome as feedback for model and policy review."],
    contribution:["Analysed commercial and operational signals relevant to pricing decisions.","Supported data / ML design for dynamic-pricing and recommendation workflows.","Translated model output into an operational decision path with business-rule controls.","Connected analytical recommendations to business KPIs and user feedback rather than treating model output as the final product."],
    runtime:[["Context","Route / voyage / customer context","Assemble the decision context for the commercial request.","data"],["Features","Demand + history + capacity signals","Create standardised, time-aware features for the pricing decision.","process"],["Forecast","Expected demand / behaviour","Estimate the future signal relevant to the price decision.","ai"],["Recommend","Model + rules","Generate a price or pricing band inside approved commercial guardrails.","ai"],["Explain","Drivers / reason codes","Expose the main factors and constraints behind the recommendation.","control"],["Review","Commercial decision","Allow accountable acceptance or override for material cases.","human"],["Learn","Outcome feedback","Track acceptance, conversion, yield and overrides for future tuning.","outcome"]],
    architecture:[["SOURCES","Demand · route · voyage · customer","Commercial / operational context"],["FEATURE LAYER","Time-aware analytical features","Reusable model input"],["FORECAST","Demand / behaviour model","Future signal"],["PRICING MODEL","Recommendation logic","Decision signal"],["GUARDRAILS","Commercial rules · limits","Governance"],["EXPLAIN","Drivers · reason codes","User trust"],["DECISION","Commercial user / API","Controlled price action"],["FEEDBACK","Quote / booking / override outcome","Continuous learning"]],
    controls:["Time leakage prevention","Feature freshness","Forecast back-test","Commercial price bounds","Override trace","Reason codes","Model versioning","Outcome monitoring"],
    toolGroups:[["Analytics",["Python","SQL","Forecasting","Feature engineering"]],["Decisioning",["Dynamic pricing","Rules / guardrails","Reason codes","Override path"]],["Measurement",["Acceptance","Conversion","Yield","Forecast error","Override rate"]]],
    artifacts:["Pricing feature map","Model / rule design","Guardrail matrix","Decision-flow diagram","Driver view","Override log","Outcome dashboard","Model review"],
    decisions:["Treat price recommendation as one input to a governed commercial decision, not a black-box answer.","Prevent future information from leaking into training or back-testing.","Make model drivers and business constraints visible to the user.","Use accepted, rejected and overridden decisions as evidence for continuous improvement."]
  },
  {
    id:"data-ai-governance", order:9, company:"Cross-project operating model", category:"governance", featured:false,
    kicker:"DATA + MODEL GOVERNANCE", title:"Production Monitoring, Lineage & Decision Controls",
    subtitle:"data quality · RBAC · lineage · model evaluation · drift · audit · support-to-backlog",
    metric:"E2E", metricLabel:"production control plane", scale:"Data pipelines · BI · ML · AI workflows",
    roleSummary:"Built governance into the delivery lifecycle so data and model products remain understandable, monitored and supportable after launch.",
    impact:"A production analytical system is only credible when users can answer: where did this data come from, is it fresh, what changed, who can access it, how is the model behaving and what happens when something goes wrong?",
    tags:["Data Governance","Model Governance","RBAC","Lineage","Monitoring","Drift","Audit","Runbooks"],
    cardFlow:["Own","Observe","Control","Respond","Improve"],
    problem:"Analytics platforms often fail after go-live because ownership, freshness, model behaviour, access and incident handling were not designed with the product.",
    before:["Ownership lived in individual knowledge.","Pipeline failures were discovered by users.","Model performance could degrade silently.","Permissions and documentation drifted as platforms scaled.","Recurring support issues did not systematically improve the product."],
    after:["Owners and criticality are explicit for datasets and models.","Freshness, quality, failures and model metrics are monitored.","RBAC and audit logs protect sensitive analytical products.","Runbooks define response and escalation.","Support signals become structured backlog and governance improvements."],
    beforeArchitecture:["Build","Release","Hope","User finds issue","Manual fix"],
    afterArchitecture:["Own","Monitor","Alert","Respond","Learn","Improve"],
    architectureChange:["Add a control plane across data, model and application layers.","Define ownership and service expectations before release.","Monitor model behaviour separately from pipeline health.","Capture incident and support evidence as inputs to continuous improvement."],
    contribution:["Maintained data-quality and governance controls across enterprise analytics platforms.","Managed documentation, access and operational monitoring patterns.","Tracked platform usage and support signals across scaled deployments.","Connected recurring issues to improvement priorities rather than treating them as isolated tickets."],
    runtime:[["Register","Owner + criticality","Define who owns the product, its consumers and service expectations.","control"],["Observe","Freshness + quality","Continuously monitor data and pipeline behaviour.","data"],["Evaluate","Model metrics","Track prediction quality, drift and decision outcomes where ML is used.","ai"],["Alert","Incident signal","Notify the right owner with enough context to diagnose quickly.","system"],["Respond","Runbook + escalation","Contain impact, correct the issue and document the decision.","human"],["Review","Root cause","Identify whether the failure came from source, logic, model, access or process.","process"],["Improve","Backlog / control update","Change the product, rule or operating model to prevent recurrence.","outcome"]],
    architecture:[["CATALOG","Owner · criticality · metadata","Governed inventory"],["DATA MONITOR","Freshness · volume · quality","Pipeline health"],["MODEL MONITOR","Performance · drift · bias","ML health"],["SECURITY","RBAC · secrets · audit","Access control"],["ALERTING","Incident routing","Operational response"],["RUNBOOK","Diagnosis + recovery","Controlled handling"],["FEEDBACK","Support / incident themes","Continuous improvement"]],
    controls:["Ownership","Data freshness","Quality thresholds","Model drift","Access review","Audit logs","Alert routing","Runbooks","Incident review","Change history"],
    toolGroups:[["Governance",["DataHub","Metadata","Lineage","RBAC"]],["Monitoring",["Freshness","Quality metrics","Model metrics","Alerts"]],["Operations",["Runbooks","Incident review","Support analysis","Backlog"]]],
    artifacts:["Data / model inventory","Ownership matrix","Quality dashboard","Model monitor","Access review","Incident runbook","Root-cause review","Improvement backlog"],
    decisions:["If a data product cannot be operated safely, it is not finished.","Monitor pipeline health, data quality and model behaviour as different failure modes.","Keep access and lineage visible for auditability.","Use recurring incidents to change the system, not only resolve the ticket."]
  }
];
